// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	greet "github.com/supermicah/dionysus/api/biz/model/greet"
)

// Greet .
// @router greet [GET]
func Greet(_ context.Context, c *app.RequestContext) {
	var err error
	var req greet.GreetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(greet.GreetResponse)

	c.JSON(consts.StatusOK, resp)
}
