// Code generated by thriftgo (0.3.2). DO NOT EDIT.

package rpc

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/supermicah/dionysus/rpc/kitex_gen/greet"
)

type Dionysus interface {
	Greet(ctx context.Context, req *greet.GreetRequest) (r *greet.GreetResponse, err error)
}

type DionysusClient struct {
	c thrift.TClient
}

func NewDionysusClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *DionysusClient {
	return &DionysusClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewDionysusClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *DionysusClient {
	return &DionysusClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewDionysusClient(c thrift.TClient) *DionysusClient {
	return &DionysusClient{
		c: c,
	}
}

func (p *DionysusClient) Client_() thrift.TClient {
	return p.c
}

func (p *DionysusClient) Greet(ctx context.Context, req *greet.GreetRequest) (r *greet.GreetResponse, err error) {
	var _args DionysusGreetArgs
	_args.Req = req
	var _result DionysusGreetResult
	if err = p.Client_().Call(ctx, "greet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type DionysusProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      Dionysus
}

func (p *DionysusProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *DionysusProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *DionysusProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewDionysusProcessor(handler Dionysus) *DionysusProcessor {
	self := &DionysusProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("greet", &dionysusProcessorGreet{handler: handler})
	return self
}
func (p *DionysusProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type dionysusProcessorGreet struct {
	handler Dionysus
}

func (p *dionysusProcessorGreet) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := DionysusGreetArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("greet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := DionysusGreetResult{}
	var retval *greet.GreetResponse
	if retval, err2 = p.handler.Greet(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing greet: "+err2.Error())
		oprot.WriteMessageBegin("greet", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("greet", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type DionysusGreetArgs struct {
	Req *greet.GreetRequest `thrift:"req,1" frugal:"1,default,greet.GreetRequest" json:"req"`
}

func NewDionysusGreetArgs() *DionysusGreetArgs {
	return &DionysusGreetArgs{}
}

func (p *DionysusGreetArgs) InitDefault() {
	*p = DionysusGreetArgs{}
}

var DionysusGreetArgs_Req_DEFAULT *greet.GreetRequest

func (p *DionysusGreetArgs) GetReq() (v *greet.GreetRequest) {
	if !p.IsSetReq() {
		return DionysusGreetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DionysusGreetArgs) SetReq(val *greet.GreetRequest) {
	p.Req = val
}

var fieldIDToName_DionysusGreetArgs = map[int16]string{
	1: "req",
}

func (p *DionysusGreetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DionysusGreetArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_DionysusGreetArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *DionysusGreetArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = greet.NewGreetRequest()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *DionysusGreetArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("greet_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *DionysusGreetArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *DionysusGreetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DionysusGreetArgs(%+v)", *p)
}

func (p *DionysusGreetArgs) DeepEqual(ano *DionysusGreetArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *DionysusGreetArgs) Field1DeepEqual(src *greet.GreetRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type DionysusGreetResult struct {
	Success *greet.GreetResponse `thrift:"success,0,optional" frugal:"0,optional,greet.GreetResponse" json:"success,omitempty"`
}

func NewDionysusGreetResult() *DionysusGreetResult {
	return &DionysusGreetResult{}
}

func (p *DionysusGreetResult) InitDefault() {
	*p = DionysusGreetResult{}
}

var DionysusGreetResult_Success_DEFAULT *greet.GreetResponse

func (p *DionysusGreetResult) GetSuccess() (v *greet.GreetResponse) {
	if !p.IsSetSuccess() {
		return DionysusGreetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DionysusGreetResult) SetSuccess(x interface{}) {
	p.Success = x.(*greet.GreetResponse)
}

var fieldIDToName_DionysusGreetResult = map[int16]string{
	0: "success",
}

func (p *DionysusGreetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DionysusGreetResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else {
				if err = iprot.Skip(fieldTypeId); err != nil {
					goto SkipFieldError
				}
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}

		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_DionysusGreetResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *DionysusGreetResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = greet.NewGreetResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *DionysusGreetResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("greet_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}

	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *DionysusGreetResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *DionysusGreetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DionysusGreetResult(%+v)", *p)
}

func (p *DionysusGreetResult) DeepEqual(ano *DionysusGreetResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *DionysusGreetResult) Field0DeepEqual(src *greet.GreetResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
