// Code generated by Kitex v0.7.3. DO NOT EDIT.

package dionysus

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	greet "github.com/supermicah/dionysus/rpc/kitex_gen/greet"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Greet(ctx context.Context, req *greet.GreetRequest, callOptions ...callopt.Option) (r *greet.GreetResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDionysusClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDionysusClient struct {
	*kClient
}

func (p *kDionysusClient) Greet(ctx context.Context, req *greet.GreetRequest, callOptions ...callopt.Option) (r *greet.GreetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Greet(ctx, req)
}
